spring:
    application:
        name: notification-service

    config:
      import: configserver:http://localhost:8888

    cloud:
      config:
        uri: http://localhost:8888
        label: main



